-- Do not use this file 

-- Seed data for tables 

-- Users

INSERT INTO users (name, password, email, tutor, bio) VALUES ('John Cynn', 'password', 'jcynn@gmail.com', 0, "I graduated from Columbia University with a PhD degree in Physics and I got a Master's degree in Applied Math from Moscow Institute of Physics and Technology.");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Michael Cortez', 'password', 'mcortez@gmail.com', 1, "I am currently an EdM student in Applied Linguistics at Teachers College at Columbia University. I graduated from the University of Florida in 2008 with a major in Spanish and minors in English and Education. In 2015 I completed my MA degree at the University of Sevilla in Spain where I studied the teaching of both English and Spanish as foreign languages. I have been teaching ESL/EFL since 2011. I have taught ESL at the English Language Institute at the University of Florida and have had the wonderful experience of living in Spain for over 4 years and teaching EFL in both private and public schools to students of all ages. Currently, I work part time for the Community Impact program as an ESL teacher trainer. I am truly passionate about teaching and particularly the learning of languages. I love learning languages myself and love to help others in their pursuit of language learning. ");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Hany Rostom', 'password', 'hrostom@gmail.com', 0, "Hi! I recently graduated cum laude from the University of Notre Dame with a B.B.A. in Finance and a minor in Chinese. I have been a peer tutor in college for several business classes including Finance, Statistics, and Economics. I graduated from Stuyvesant High School in 2014 and have 8 years of experience teaching at various tutoring/prep centers. I've also operated my own tutoring center in Brooklyn for 2 years.");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Nick Boylan', 'password', 'nboylan@gmail.com', 0, 'Hi! I recently graduated from Columbia University with a double major in biology (pre-med) and political science, and I am currently working as Massachusetts General Hospital.');
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Laurents Mohr', 'password', 'laurents@gmail.com', 0, 'I am currently a student at Columbia University double majoring in Mathematics and Chemical Physics. I have four years of professional tutoring experience and have helped students develop their ability to learn and retain information.');
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Lina Lei', 'password', 'lina@gmail.com', 1, 'Background in environmental health, science research, and startups. Previous Chief Operating Officer at Audicus.com with strengths in analytics and strategy.');
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Wei Gao', 'password', 'wei@gmail.com', 0, "Hey! I'm a current student at Columbia studying Computational Sociology—which involves a mix of Computer Science, Statistics, and of course Sociology. Outside of my studies, I am also the president of the French Cultural Society and intern at a law firm.");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Rose Lin', 'password', 'rose@gmail.com', 1, "Hey there! I am an 8th grade English Language Arts Teacher in living in Brooklyn. However, I have strong knowledge in a vast number of content areas and skills. Over my past 4 years of teaching, my content areas of specialty have been the english language arts, including writing, reading, and respective test prep skills as well as arts education, including the adobe programs, illustration, and fine arts. I also have strong knowledge in social studies and sciences. If you are interested in working with me, please feel free to reach out!");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Mandy Mak', 'password', 'mandy@gmail.com', 0, "Hey! I'm attending medical school at Weill Cornell Medical College on the UES, and I graduated cum laude from Columbia University in 2016 with departmental honors in Ecology, Evolution, and Environmental Biology.");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Tom Wagner', 'password', 'tom@gmail.com', 1, 'Hello everyone! I grew up in the foothills of East Tennessee, went to college at Emory University, earned my BS in Biology and my BA in Philosophy, then went to Duke University, and earned my MA in Bioethics and Health Policy.');
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Jessica Wolvington', 'password', 'jessica@gmail.com', 1, 'I went to NYU for undergrad, and then moved to London for my masters at the University College of London. I was an elementary school teacher before deciding to take the plunge to start learning how to code. Also, I love traveling, and try to do so whenever I get the chance.');
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Nick Rogers', 'password', 'nick@gmail.com', 0, 'I am an undergraduate junior at Columbia majoring in applied physics. This field of study requires me to draw on my knowledge of math and also to keep an open mind for new concepts. One of my favorite aspects of this is getting comfortable with a new idea or technique. I love figuring out how to use what I already know to solve different kinds of problems, and I truly enjoy helping others do just that.');
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Joseph Martin', 'password', 'joseph@gmail.com', 1, 'Before I joined Hack Reactor (way back when it was MakerSquare, New York) I was a designer and developer in Los Angeles, building ERP and tracking software for movie studios like Lionsgate and Netflix. It was a lot of database design, SQL, Java /Groovy and when I was lucky, HTML + JS; I also got to hang out at the studio offices, which was fun. Before that, I was studying communications and media at UC Berkeley - go bears!');
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Koichi Sakamaki', 'password', 'koichi@gmail.com', 0, "Hi! My name is Koichi and I'm a junior at Barnard studying Biology and Computer Science. I also have an interest in Education.");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('David Baek', 'password', 'davidb@hotmail.com', 1, "I am a PhD student studying statistics. I really enjoy teaching and tutor in statistics, regression, and math (from algebra and geometry to calculus and linear algebra). I can also help doctoral candidates run, interpret, and report their statistical analysis. I usually suggest that any prospective student go through a practice run before we commit to anything more, and guarantee your money back if you are not satisfied with my services.");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Seamus Martin', 'password', 'seamus@gmail.com', 1, "Hey there! My name is Seamus, and I'm a tutor who is interested in helping people reach their full potential. I am in my second year of law school, and I have over 3 years of tutoring experience. I have a strong background in reading, writing (essay, research paper, etc.), and history. I am additionally well versed in test prep for college (act, PSAT, sat) and applying for college, jobs, or scholarships. I'd love to help However I can!");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Isto Barton', 'password', 'isto@gmail.com', 1, "I got a 2300 on my SATs, a 35 on my ACT, 95th percentile on my GRE, and worked as an Alzheimer's researcher for three years at Langone Medical Center.");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Philip Gonzalez', 'password', 'philip@gmail.com', 0, "My name is Philip and I am an engineer. I have an undergraduate degree in Chemical Engineering and a masters degree in Environmental Engineering with a concentration in Groundwater and Soil Pollution Control. I am passionate about teaching and sharing my expansive knowledge of math, science, and engineering with students.");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Jack Lim', 'password', 'jacklim@gmail.com', 0, "A Biology teacher at daytime, master student and Tutor at night time, and math teacher on weekend. I am specializing in helping high school students getting through their regents, SAT, and AP courses and preparing them to get to their dream colleges. My thousands of hours of tutoring and proven techniques in effectively scoring high have helped hundreds of students getting through their academics and achieving success.");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Jason McCutchan', 'password', 'jason@gmail.com', 0, "In my 2+ years at Guideline, I've taught everything from SAT/ACT/SSHAT classes to one-on-one prep sessions for GED, AP, and NYS Regents. Additionally, I've provided mentorship to various ex-students for college counseling, personal essay writing, and language lessons. Outside of Guideline, I've assisted with state examination and homework help for local Elementary / M.S. students./-All my rates are negotiable; I'll provide one free hour to meet and understand the level you or your child is at through a short diagnostic. After, I'd be able to offer a flat rate for further sessions after figuring out a time frame for skill building and practice");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Jeff Anderson', 'password', 'jeff@gmail.com', 1, "I scored in the upper 99th percentile on the LSAT. I have interviewed with nearly every major law firm and will serve as a judicial extern for SDNY in the fall. I assure you I am qualified to instruct you, but more than this, I simply would love to. I have been a professional tutor for many years and there is nothing I enjoy doing more than helping others achieve their goals, especially when they might seem just barely out of reach.");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Jon Izak', 'password', 'jon@gmail.com', 0, "I received my BS in Biochemistry and Bioinformatics from Ramapo and attained an MS from Rutgers in Biomedical Informatics. I graduated with an MS in Computational Biology and Bioinformatics from Yale in 2014. I have extensive teaching experience: I served as a Supplemental Instructor for 5 semesters in Elementary Probability & Statistics at Ramapo and worked as an Anatomy & Physiology lecturer at Success Training College, and an Instrumental Analysis lecturer at Terreve College. I also tutored Math in the Bahamas from 2009-2010.");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Jill Ryan', 'password', 'jill@gmail.com', 0, "Finished up at Dartmouth with a 7.4 GPA and also go my PhD from Yale in Greek machine learning.");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Bill BoBaggins', 'password', 'bill@gmail.com', 0, "Mathmatics professor at Columbia, graduated from Harvard sometime in the early 20s");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Yolo Ronaldhino', 'password', 'yolo@gmail.com', 0, "Comp-Sci wunderkid, have been building full-stack appliations since 1994");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Tennessee Williams', 'password', 'tennessee@gmail.com', 0, "Avid ortnothologist, part-time bare-knuckle boxer");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Hennessey Williams', 'password', 'hennessey@gmail.com', 0, "Avid ornothologist, part-time bare-knuckle boxer, LSAT aficionado");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Jack Ryan', 'password', 'jack@gmail.com', 0, "I am a character in a book");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Tom Clancy', 'password', 'tomclancy@gmail.com', 0, "Skilled writer with a passion for thrillers");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Vladimir Putin', 'password', 'damian@gmail.com', 0, "Just tryna make ends meet");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Buck Compton', 'password', 'buck@gmail.com', 0, "really hoping to do well on something");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Shifty Powers', 'password', 'shifty@gmail.com', 0, "Whether its learning full-stack JavaScript or translating Spanish literature into Japanese, I'm your guy");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Richard Winters', 'password', 'richard@gmail.com', 0, "My ability to lead an assault on a larger enemy force firmly-dug into a fixed position, with a smaller force of my own, is un-paralled. nbd.");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Kaitlyn Wingo', 'password', 'kaitlyn@gmail.com', 0, "Skilled dentist and moderately talented basketball player");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Rango Cunningham', 'password', 'rango@gmail.com', 0, "Finished top of my class at MIT, mathematics is my passion");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('John Thompson', 'password', 'michael@gmail.com', 0, "UC-Berkeley undergrad, received my PhD in Biology from the Univeristy of Chicago");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Conor MacGregor', 'password', 'conor@gmail.com', 0, "When I am not in a cage, im taking professional educational exams for kicks");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Marquis de Lafayette', 'password', 'marquis@gmail.com', 0, "I'm a big America guy");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Jeremy Hunter', 'password', 'jhunter@gmail.com', 1, "Masters student in Computer Science at NYU. Extensive tutoring experience with high school and college students for SHSAT, SAT, ACT, SAT II.");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Mickey Marks', 'password', 'mickmark@gmail.com', 1, "Hello! I recently graduated from Cornell University's SC Johnson College of Business with a major in Hotel Administration. I have over 5 years of tutoring and teaching experience. During my time at Cornell, I served as a TA for business courses such as Marketing and Consumer Behavior. I have also spent time as a camp counselor for elementary school students. I mainly focus on tutoring high school students in standardized testing and college applications. Specifically, I assist with ACT/SAT Reading and Math, AP Literature and Language & Composition, and Common App writing.");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Ian Cummings', 'password', 'ianC@gmail.com', 1, "I am a math major graduated in 2014 from Columbia. I have been tutoring kids since junior year of college. My specialties lie in any quantitative subject but I do have a strong hold of qualitative subjects like Econ and finance.");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Lawrence Heath', 'password', 'lawrenceH@gmail.com', 1, 'I am currently a grad student at NYU studying Marketing/Brand Management. I have a degree in BFA Graphic Design from the School of Visual Arts(2010) and worked for various corporate level brands for 6 years in the creative/digital marketing industry.');
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Jane Dee', 'password', 'janeDee@gmail.com', 1, 'Hi! My name is Jane, I am French and I moved to NY four years ago for college. I recently graduated from Fordham Gabelli School of Business where I optioned a degree in Marketing and Art History. Throughout my education back in France and at Fordham I received several diplomas such as the IGCSE (English) the Dele C1 (Spanish) and the French Baccalaureate with the International option. Because of my wide range of academic skills and my past experience tutoring, I truly believe I can help you.');
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Anna Blakely', 'password', 'annaB@gmail.com', 1, 'Hello! I am a senior undergraduate student at St. Johns University studying Computer Science and Business Administration. I have been tutoring for 6 years now. I currently tutor SAT Math, SHSAT, Regents, Elementary through High School subjects and lastly Mandarin. I took nine years of Mandarin, so I am fluent in speaking, reading and writing it. My previous clients range from beginners to intermediate students. I can do translations from simple conversations to business conversations as well.');
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Robert Joseph', 'password', 'r.joseph@gmail.com', 1, "Biology teacher at daytime, master student and Tutor at night time, and math teacher on weekend. I am specializing in helping high school students getting through their regents, SAT, and AP courses and preparing them to get to their dream colleges. My thousands of hours of tutoring and proven techniques in effectively scoring high have helped hundreds of students getting through their academics and achieving success.");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Moseph Jartin', 'password', 'moseph@gmail.com', 1, "Hello! I'm a recent graduate from Pomona College in Claremont, California. I earned a BA in Computer Science and maintained a 3.77 GPA while taking courses in a wide variety of fields, including math, psychology, and creative writing. I graduated from Stuyvesant High School in 2014 with a 96.9 GPA. While computer science and programming is my specialty, I am also highly proficient in math and writing. I look forward to working with you!");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Rahul Krishna', 'password', 'rahulk@gmail.com', 1, "I am a current Master's student in finance and quantitative methods at the Columbia University School of International and Public Affairs. Prior to attending Columbia, I ran a SAT/ACT tutoring company in Beijing for two years, where I taught in one-on-one, group, and classroom settings. I also trained dozens of other tutors, allowing me to have the ideal knowledge of what makes a great instructor. Since returning from China, I have been teaching ACT and SAT privately for an additional two years. This experience, plus my work experience in finance and trading, allows me to both recognize the exact problems that most high school students face, as well as the best ways to teach tricky math problems and other complicated ideas to my students.");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Peter Muir', 'password', 'pMuir@gmail.com', 1, 'I am currently a student at Columbia University double majoring in Mathematics and Chemical Physics. I have four years of professional tutoring experience and have helped students develop their ability to learn and retain information. I love working with others and look forward to working with all my students. I am fluent in Spanish and love Math as well as the Sciences. I can help develop ideas and work through problems in a lot of different areas of study. I have worked with students at all levels of education, from elementary school through college, throughout a range of different subjects. I also have two years experience with test prep for SAT and Math and Chemistry SAT II subject tests.');
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Talia Kahn', 'password', 'TaliaKahn@gmail.com', 1, 'Hi! I recently graduated Cornell University with a BS in Biology and have studied a wide variety of subjects since high school. I have previously tutored SAT/ACT, mathematics, and the sciences for several years, with my students ranging from elementary to college-age students. I enjoy teaching and learning and look forward to having engaging sessions to increase achievement! :)');
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Harold Kumar', 'password', 'harold.kumar@gmail.com', 1, 'I hold a Masters degree in Biotechnology from Columbia University. In college, I completed double majors in Biology and Sociology. In addition, I also finished a writing minor. I have more than two years of experiences teaching and tutoring students in various subjects. I was a lead teacher teaching SHSAT summer class at a prep school this past summer. In addition, I have been tutoring various SAT subjects privately for two years. I specialize in test prep. I am very passionate about teaching and working with students!');
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Bruce Brenner', 'password', 'bbrenner@gmail.com', 1, 'I am a math major graduated in 2014 from Columbia. I have been tutoring kids since junior year of college. My specialties lie in any quantitative subject but I do have a strong hold of qualitative subjects like Econ and finance.');
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Olivia Park', 'password', 'oliviapark@gmail.com', 1, "I am double majoring in Computer Science at the Courant Institute, as well as Business Administration with a concentration in Data Science and Computing at the Stern school of business at NYU. I have worked for tech-startups but also large companies such as Bank of America. However, now I run my own start up with the help of my co-founder.");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Donald Krump', 'password', 'donaldjkrump@aol.com', 1, "International Traveler & Owner of a travel startup, with experience in Human Resources, Marketing & many fields, I am happy to share my knowledge. Love to teach people about starting their own businesses, all things Entrepreneurship, Economics, Career Counseling, Mathematics, Communications & Psychology.");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Kevin Wang', 'password', 'kevin@gmail.com', 0, "I am from New Jersey and rreceived my BS in Kinesiology from Rutgers. In my free time I enjoy the outdoors and good game of Blockus");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Daniel Novograd', 'password', 'daniel@gmail.com', 0, "I am an associate at PolicyGenius. We are changing a massive industry by making insurance shopping faster, friendlier and more transparent for online consumers. Since our launch in 2014, we’ve achieved rapid growth in a notoriously difficult industry and established ourselves as a pioneer in a now hot sector of FinTech.");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Jear Jujaroen', 'password', 'jear@gmail.com', 0, "I am front-end engineer and I have a passion for understanding concepts at a fundamental level. I love learning new things and am exicted to share my passion with others. I am specifically interested in artifical intellegence and neural networks and enjoy designing neural networks in my free time");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Britney Nagasawa', 'password', 'britney@gmail.com', 0, "Hello! I recently graduated from the University of Hawaii Shidler College of Business with a BBA in Finance and International Business. I am a Regents Scholar and just finished my summer internship with Merrill Lynch and am looking to forward to being a full-time first year analyst for the energy markets");
INSERT INTO users (name, password, email, tutor, bio) VALUES ('Tony Xu', 'password', 'tony@gmail.com', 0, "Hello! I am currently a student at MIT. My focus is in chemical engineering and mathematics. In my free time I enjoy playing the violin in the Central Park");

-- Tests Tutors can Tutor
INSERT INTO tests (Name, Description) VALUES ('LSAT', "The Law School Admission Test (LSAT) is a half-day standardized test administered 4 times each year (6 starting in 2018-2019) at designated testing centers throughout the world. Administered by the Law School Admission Council (LSAC) for prospective law school candidates, the LSAT is designed to assess reading comprehension, logical, and verbal reasoning proficiency.");
INSERT INTO tests (Name, Description) VALUES ('SAT', "The SAT is a standardized test widely used for college admissions in the United States. Introduced in 1926, its name and scoring have changed several times; originally called the Scholastic Aptitude Test, it was later called the Scholastic Assessment Test, then the SAT I: Reasoning Test, then the SAT Reasoning Test, and now, simply the SAT.");
INSERT INTO tests (Name, Description) VALUES ('ACT', "The ACT is a standardized test used for college admissions in the United States. It was first introduced in November 1959 by University of Iowa professor Everett Franklin Lindquist as a competitor to the Scholastic Aptitude Test (SAT).[11] It is currently administered by ACT, a nonprofit organization of the same name.");
INSERT INTO tests (Name, Description) VALUES ('SSAT', "The Secondary School Admission Test (SSAT) is an admission test administered by The Enrollment Management Association in the United States to students in grades 3–11 to provide a standardized measure that will help professionals in independent or private elementary, middle, and high schools to make decisions regarding student admission.");
INSERT INTO tests (Name, Description) VALUES ('Regents', "In New York State, Regents Examinations are statewide standardized examinations in core high school subjects required for a certain Regents Diploma to graduate. To graduate, students are required to have earned appropriate credits in a number of specific subjects by passing year-long or half-year courses, after which they must pass at least five Regents examinations in some of the subject areas. For higher achieving students, a Regents with Advanced designation, and an Honor designation, are also offered. Students with disabilities or enrolled in an English as a Second Language program are able to earn a local diploma.");
INSERT INTO tests (Name, Description) VALUES ('TOEFLiBT', "The TOEFL iBT test measures your ability to use and understand English at the university level. And it evaluates how well you combine your reading, listening, speaking and writing skills to perform academic tasks.");
INSERT INTO tests (Name, Description) VALUES ('IELTS', "IELTS, the International English Language Testing System, is designed to assess the language ability of candidates who need to study or work where English is used as the language of communication. IELTS is required for entry to university in the UK and other countries.");
INSERT INTO tests (Name, Description) VALUES ('GRE', "It's the most commonly required admission test for grad school. Much like the SAT and ACT, the GRE exam is a broad assessment of your critical thinking, analytical writing, verbal reasoning, and quantitative reasoning skills — all skills developed over the course of many years.");
INSERT INTO tests (Name, Description) VALUES ('GMAT', "The Graduate Management Admission Test is a computer adaptive test intended to assess certain analytical, writing, quantitative, verbal, and reading skills in written English for use in admission to a graduate management program, such as an MBA.");
INSERT INTO tests (Name, Description) VALUES ('CFA', "The Chartered Financial Analyst (CFA) Program is a professional credential offered internationally by the American-based CFA Institute (formerly the Association for Investment Management and Research, or AIMR) to investment and financial professionals. ");
INSERT INTO tests (Name, Description) VALUES ('MCAT', "The Medical College Admission Test is a computer-based standardized examination for prospective medical students in the United States, Australia, Canada, and Caribbean Islands");
INSERT INTO tests (Name, Description) VALUES ('DAT', "The DAT is a dental education admission test designed to provide dental education programs with a means to assess program applicants' potential for success.");

-- Tutors
INSERT INTO tutors (id, Name, Bio, Price, Rating) VALUES (1, 'John Cynn', "I graduated from Columbia University with a PhD degree in Physics and I got a Master's degree in Applied Math from Moscow Institute of Physics and Technology. ", 40, 3);
INSERT INTO tutors (id, Name, Bio, Price, Rating) VALUES (2, 'Michael Cortez', "I have taught ESL at the English Language Institute at the University of Florida and have had the wonderful experience of living in Spain for over 4 years and teaching EFL in both private and public schools to students of all ages. Currently, I work part time for the Community Impact program as an ESL teacher trainer. ", 50, 3);
INSERT INTO tutors (id, Name, Bio, Price, Rating) VALUES (6, 'Lina Lei', "I am truly passionate about teaching and particularly the learning of languages. I love learning languages myself and love to help others in their pursuit of language learning. ", 60, 4);
INSERT INTO tutors (id, Name, Bio, Price, Rating) VALUES (8, 'Rose Lin', "I mainly tutor students in test prep for different levels of Math (Regents, SHSAT, SAT/ACT, SAT II). I can also help with various high school and college courses!", 45, 3);
INSERT INTO tutors (id, Name, Bio, Price, Rating) VALUES (10, 'Tom Wagner', "I graduated from Stuyvesant High School in 2014 and have 8 years of experience teaching at various tutoring/prep centers. I've also operated my own tutoring center in Brooklyn for 2 years.", 140, 3);
INSERT INTO tutors (id, Name, Bio, Price, Rating) VALUES (11, 'Jessica Wolvington', "I have had a lot of experience with tutoring the new SAT, several AP courses, essay writing, and the college application process.  ", 65, 5);
INSERT INTO tutors (id, Name, Bio, Price, Rating) VALUES (13, 'Joseph Martin', "I love working with others and look forward to working with all my students. I am fluent in Spanish and love Math as well as the Sciences. ", 70, 2);
INSERT INTO tutors (id, Name, Bio, Price, Rating) VALUES (15, 'David Baek', " I have many years of tutoring experience, and I currently teach an introductory Computer Science class at a private school on the UWS. ", 75, 3);
INSERT INTO tutors (id, Name, Bio, Price, Rating) VALUES (16, 'Seamus Martin', "I moved to New York to join a research team at Columbia conducting community-based participatory research to alleviate depression in Harlem.", 45, 1);
INSERT INTO tutors (id, Name, Bio, Price, Rating) VALUES (17, 'Isto Barton', "I hope to either go on to complete a PhD in Biology or further study education post-graduation, and I want to become a science educator in a college/university, high school, or museum. ", 30, 3);
INSERT INTO tutors (id, Name, Bio, Price, Rating) VALUES (21, 'Jeff Anderson', "I take a personalized approach to teaching and tailor my style to the student and tend to ask a lot of questions to check l for comprehension as we learn together.", 55, 3);
INSERT INTO tutors (id, Name, Bio, Price, Rating) VALUES (39, 'Jeremy Hunter', "Masters student in Computer Science at NYU. Extensive tutoring experience with high school and college students for SHSAT, SAT, ACT, SAT II.", 100, 2);
INSERT INTO tutors (id, Name, Bio, Price, Rating) VALUES (40, 'Mickey Marks', "Hello! I recently graduated from Cornell University's SC Johnson College of Business with a major in Hotel Administration. I have over 5 years of tutoring and teaching experience. During my time at Cornell, I served as a TA for business courses such as Marketing and Consumer Behavior. I have also spent time as a camp counselor for elementary school students. I mainly focus on tutoring high school students in standardized testing and college applications. Specifically, I assist with ACT/SAT Reading and Math, AP Literature and Language & Composition, and Common App writing.", 50, 3);
INSERT INTO tutors (id, Name, Bio, Price, Rating) VALUES (41, 'Ian Cummings', "I am a math major graduated in 2014 from Columbia. I have been tutoring kids since junior year of college. My specialties lie in any quantitative subject but I do have a strong hold of qualitative subjects like Econ and finance.", 75, 4);
INSERT INTO tutors (id, Name, Bio, Price, Rating) VALUES (42, 'Lawrence Heath', 'I am currently a grad student at NYU studying Marketing/Brand Management. I have a degree in BFA Graphic Design from the School of Visual Arts(2010) and worked for various corporate level brands for 6 years in the creative/digital marketing industry.', 70, 3);
INSERT INTO tutors (id, Name, Bio, Price, Rating) VALUES (43, 'Jane Dee', 'Hi! My name is Jane, I am French and I moved to NY four years ago for college. I recently graduated from Fordham Gabelli School of Business where I optioned a degree in Marketing and Art History. Throughout my education back in France and at Fordham I received several diplomas such as the IGCSE (English) the Dele C1 (Spanish) and the French Baccalaureate with the International option. Because of my wide range of academic skills and my past experience tutoring, I truly believe I can help you.', 80, 3);
INSERT INTO tutors (id, Name, Bio, Price, Rating) VALUES (44, 'Anna Blakely', 'Hello! I am a senior undergraduate student at St. Johns University studying Computer Science and Business Administration. I have been tutoring for 6 years now. I currently tutor SAT Math, SHSAT, Regents, Elementary through High School subjects and lastly Mandarin. I took nine years of Mandarin, so I am fluent in speaking, reading and writing it. My previous clients range from beginners to intermediate students. I can do translations from simple conversations to business conversations as well.', 60, 4);
INSERT INTO tutors (id, Name, Bio, Price, Rating) VALUES (45, 'Robert Joseph', "Biology teacher at daytime, master student and Tutor at night time, and math teacher on weekend. I am specializing in helping high school students getting through their regents, SAT, and AP courses and preparing them to get to their dream colleges. My thousands of hours of tutoring and proven techniques in effectively scoring high have helped hundreds of students getting through their academics and achieving success.", 65, 2);
INSERT INTO tutors (id, Name, Bio, Price, Rating) VALUES (46, 'Moseph Jartin', "Hello! I'm a recent graduate from Pomona College in Claremont, California. I earned a BA in Computer Science and maintained a 3.77 GPA while taking courses in a wide variety of fields, including math, psychology, and creative writing. I graduated from Stuyvesant High School in 2014 with a 96.9 GPA. While computer science and programming is my specialty, I am also highly proficient in math and writing. I look forward to working with you!", 70, 1);
INSERT INTO tutors (id, Name, Bio, Price, Rating) VALUES (47, 'Rahul Krishna', "I am a current Master's student in finance and quantitative methods at the Columbia University School of International and Public Affairs. Prior to attending Columbia, I ran a SAT/ACT tutoring company in Beijing for two years, where I taught in one-on-one, group, and classroom settings. I also trained dozens of other tutors, allowing me to have the ideal knowledge of what makes a great instructor. Since returning from China, I have been teaching ACT and SAT privately for an additional two years. This experience, plus my work experience in finance and trading, allows me to both recognize the exact problems that most high school students face, as well as the best ways to teach tricky math problems and other complicated ideas to my students.", 85, 3);
INSERT INTO tutors (id, Name, Bio, Price, Rating) VALUES (48, 'Peter Muir', 'I am currently a student at Columbia University double majoring in Mathematics and Chemical Physics. I have four years of professional tutoring experience and have helped students develop their ability to learn and retain information. I love working with others and look forward to working with all my students. I am fluent in Spanish and love Math as well as the Sciences. I can help develop ideas and work through problems in a lot of different areas of study. I have worked with students at all levels of education, from elementary school through college, throughout a range of different subjects. I also have two years experience with test prep for SAT and Math and Chemistry SAT II subject tests.', 80, 2);
INSERT INTO tutors (id, Name, Bio, Price, Rating) VALUES (49, 'Talia Kahn', 'Hi! I recently graduated Cornell University with a BS in Biology and have studied a wide variety of subjects since high school. I have previously tutored SAT/ACT, mathematics, and the sciences for several years, with my students ranging from elementary to college-age students. I enjoy teaching and learning and look forward to having engaging sessions to increase achievement! :)', 55, 4);
INSERT INTO tutors (id, Name, Bio, Price, Rating) VALUES (50, 'Harold Kumar', 'I hold a Masters degree in Biotechnology from Columbia University. In college, I completed double majors in Biology and Sociology. In addition, I also finished a writing minor. I have more than two years of experiences teaching and tutoring students in various subjects. I was a lead teacher teaching SHSAT summer class at a prep school this past summer. In addition, I have been tutoring various SAT subjects privately for two years. I specialize in test prep. I am very passionate about teaching and working with students!', 110, 3);
INSERT INTO tutors (id, Name, Bio, Price, Rating) VALUES (51, 'Bruce Brenner', 'I am a math major graduated in 2014 from Columbia. I have been tutoring kids since junior year of college. My specialties lie in any quantitative subject but I do have a strong hold of qualitative subjects like Econ and finance.', 50, 3);
INSERT INTO tutors (id, Name, Bio, Price, Rating) VALUES (52, 'Olivia Park', "I am double majoring in Computer Science at the Courant Institute, as well as Business Administration with a concentration in Data Science and Computing at the Stern school of business at NYU. I have worked for tech-startups but also large companies such as Bank of America. However, now I run my own start up with the help of my co-founder.", 115, 4);
INSERT INTO tutors (id, Name, Bio, Price, Rating) VALUES (53, 'Donald Krump', "International Traveler & Owner of a travel startup, with experience in Human Resources, Marketing & many fields, I am happy to share my knowledge. Love to teach people about starting their own businesses, all things Entrepreneurship, Economics, Career Counseling, Mathematics, Communications & Psychology.", 120, 2);

-- Photos
INSERT INTO photos (user_id, location) VALUES (1, 'https://s3.amazonaws.com/tutorstream-files/download+(1).jpeg');
INSERT INTO photos (user_id, location) VALUES (2, 'https://s3.amazonaws.com/tutorstream-files/images+(6).jpeg');
INSERT INTO photos (user_id, location) VALUES (6, 'https://s3.amazonaws.com/tutorstream-files/female.jpeg');
INSERT INTO photos (user_id, location) VALUES (8, 'https://s3.amazonaws.com/tutorstream-files/images+(1).jpeg');
INSERT INTO photos (user_id, location) VALUES (10, 'https://s3.amazonaws.com/tutorstream-files/download.jpeg');
INSERT INTO photos (user_id, location) VALUES (11, 'https://s3.amazonaws.com/tutorstream-files/images.jpeg');
INSERT INTO photos (user_id, location) VALUES (13, 'https://s3.amazonaws.com/tutorstream-files/images+(2).jpeg');
INSERT INTO photos (user_id, location) VALUES (15, 'https://s3.amazonaws.com/tutorstream-files/images+(4).jpeg');
INSERT INTO photos (user_id, location) VALUES (16, 'https://s3.amazonaws.com/tutorstream-files/images+(3).jpeg');
INSERT INTO photos (user_id, location) VALUES (17, 'https://s3.amazonaws.com/tutorstream-files/images+(5).jpeg');
INSERT INTO photos (user_id, location) VALUES (21, 'https://s3.amazonaws.com/tutorstream-files/guy-fieri.jpeg');
INSERT INTO photos (user_id, location) VALUES (39, 'https://s3.amazonaws.com/tutorstream-files/images+(19).jpeg');
INSERT INTO photos (user_id, location) VALUES (40, 'https://s3.amazonaws.com/tutorstream-files/download+(3).jpeg');
INSERT INTO photos (user_id, location) VALUES (41, 'https://s3.amazonaws.com/tutorstream-files/images+(11).jpeg');
INSERT INTO photos (user_id, location) VALUES (42, 'https://s3.amazonaws.com/tutorstream-files/images+(14).jpeg');
INSERT INTO photos (user_id, location) VALUES (43, 'https://s3.amazonaws.com/tutorstream-files/download+(2).jpeg');
INSERT INTO photos (user_id, location) VALUES (44, 'https://s3.amazonaws.com/tutorstream-files/images+(7).jpeg');
INSERT INTO photos (user_id, location) VALUES (45, 'https://s3.amazonaws.com/tutorstream-files/images+(15).jpeg');
INSERT INTO photos (user_id, location) VALUES (46, 'https://s3.amazonaws.com/tutorstream-files/images+(12).jpeg');
INSERT INTO photos (user_id, location) VALUES (47, 'https://s3.amazonaws.com/tutorstream-files/images+(13).jpeg');
INSERT INTO photos (user_id, location) VALUES (48, 'https://s3.amazonaws.com/tutorstream-files/images+(16).jpeg');
INSERT INTO photos (user_id, location) VALUES (49, 'https://s3.amazonaws.com/tutorstream-files/images+(8).jpeg');
INSERT INTO photos (user_id, location) VALUES (50, 'https://s3.amazonaws.com/tutorstream-files/images+(18).jpeg');
INSERT INTO photos (user_id, location) VALUES (51, 'https://s3.amazonaws.com/tutorstream-files/images+(17).jpeg');
INSERT INTO photos (user_id, location) VALUES (52, 'https://s3.amazonaws.com/tutorstream-files/images+(9).jpeg');
INSERT INTO photos (user_id, location) VALUES (53, 'https://s3.amazonaws.com/tutorstream-files/images+(10).jpeg');


-- Tutor Tests
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (1, 11);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (2, 10);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (6, 9);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (8, 8);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (10, 7);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (11, 6);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (13, 5);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (15, 4);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (16, 3);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (17, 2);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (21, 1);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (1, 12);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (2, 12);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (10, 12);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (13, 12);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (39, 2);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (39, 3);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (39, 4);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (40, 9);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (40, 10);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (40, 8);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (41, 2);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (41, 5);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (42, 9);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (42, 10);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (42, 6);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (43, 4);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (43, 6);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (43, 7);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (44, 2);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (45, 12);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (45, 11);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (45, 2);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (45, 3);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (45, 4);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (45, 7);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (45, 6);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (46, 2);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (46, 3);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (46, 4);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (46, 5);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (47, 8);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (47, 10);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (48, 10);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (49, 11);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (49, 12);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (49, 5);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (49, 4);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (49, 2);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (49, 3);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (49, 4);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (50, 8);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (50, 9);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (51, 2);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (51, 4);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (51, 10);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (52, 1);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (52, 9);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (52, 8);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (53, 1);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (53, 5);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (53, 6);
INSERT INTO tutor_tests (tutor_id, test_id) VALUES (53, 7);

-- Feedback
INSERT INTO feedback (user_id, tutor_id, rating, content) VALUES (12, 8, 5, 'Rose took the time to get into the details about my test prep');
INSERT INTO feedback (user_id, tutor_id, rating, content) VALUES (2, 8, 4, 'Absolutely worth your time! I had issues grasping the material but Rose really kept me accountable. I spent 3 weeks with her and my score doubled');
INSERT INTO feedback (user_id, tutor_id, rating, content) VALUES (4, 8, 4, 'She is amazing! I have been with her for a 4 months now and I have improved after each session. She really cares about your outcome so she will keep you accountable');
INSERT INTO feedback (user_id, tutor_id, rating, content) VALUES (20, 15, 5, 'Before I met David, I had little to no motivation. Besides being really good at explaining fundamentals, David really helped motivate me to give my best');
INSERT INTO feedback (user_id, tutor_id, rating, content) VALUES (23, 15, 5, 'If I could give more than 5 stars, I would! David is outstanding and personable');
INSERT INTO feedback (user_id, tutor_id, rating, content) VALUES (26, 15, 4, 'Very professional and goes out of his way to find a time that works for you, a lot better than tutors I find on Gooroo');
INSERT INTO feedback (user_id, tutor_id, rating, content) VALUES (31, 11, 4, 'Very professional and goes above and beyond to find a time that works for you, much better than tutors I find on Gooroo');
INSERT INTO feedback (user_id, tutor_id, rating, content) VALUES (27, 11, 4, 'Jessica was outstanding. Her energy motivated me to study');
INSERT INTO feedback (user_id, tutor_id, rating, content) VALUES (29, 11, 4, 'I have been with TutorStream for a few a weeks, and she is the best Tutor I have had!');
INSERT INTO feedback (user_id, tutor_id, rating, content) VALUES (31, 16, 4, 'Seamus is has deep understanding of the material and really enjoys when you progress');
INSERT INTO feedback (user_id, tutor_id, rating, content) VALUES (27, 16, 5, 'Seamus is patient and explains the material in a way that is not too complicated.');
INSERT INTO feedback (user_id, tutor_id, rating, content) VALUES (29, 16, 4, 'Absolutely outstanding! Thanks so much Seamus!');

-- Sessions 
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (2, 11, 3, '2018-10-10', '10:20:05', 0, 65);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (2, 11, 7, '2018-11-03', '02:20:05',0, 65);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (2, 11, 7, '2018-09-03', '04:05:05',0, 65);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (1, 13, 35, '2019-11-05', '06:05:07',0, 70);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (2, 16, 34, '2019-11-05', '10:05:05',0, 45);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (3, 17, 33, '2019-11-05', '07:05:05',0, 30);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (4, 21, 32, '2019-11-05', '02:05:05',0, 55);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (5, 10, 31, '2019-11-05', '01:05:05',0, 140);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (6, 6, 30, '2019-11-05', '04:05:05',0, 60);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (7, 2, 28, '2019-11-05', '01:05:05',0, 50);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (8, 8, 25, '2019-11-05', '06:05:05',0, 45);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (9, 1, 24, '2019-11-05', '04:05:05',0, 40);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (10, 17, 29, '2019-11-05', '02:05:05',0, 30);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (11, 6, 27, '2019-11-05', '04:09:05',0, 60);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (12, 2, 26, '2019-11-05', '04:01:05',0, 50);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (1, 21, 23, '2019-11-05', '04:02:05',0, 55);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (1, 17, 36, '2019-11-05', '04:02:05',0, 30);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (1, 13, 35, '2019-10-05', '06:05:07',0, 70);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (2, 16, 34, '2019-02-05', '10:05:05',0, 45);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (3, 17, 33, '2019-01-05', '07:05:05',0, 30);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (4, 21, 32, '2019-04-05', '02:05:05',0, 55);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (5, 10, 31, '2019-07-05', '01:05:05',0, 140);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (6, 6, 30, '2019-08-05', '04:05:05',0, 60);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (7, 2, 28, '2019-12-05', '01:05:05',0, 50);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (8, 8, 25, '2019-10-05', '06:05:05',0, 45);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (9, 1, 24, '2019-10-05', '10:05:05',0, 40);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (10, 17, 29, '2019-09-05', '02:05:05',0, 30);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (11, 6, 27, '2019-09-05', '04:09:05',0, 60);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (12, 2, 26, '2019-08-05', '04:01:05',0, 50);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (1, 21, 23, '2019-10-10', '06:02:05',0, 55);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (1, 17, 32, '2019-11-05', '04:02:05',0, 30);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (1, 13, 35, '2019-10-05', '07:05:03',0, 70);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (2, 16, 34, '2019-02-05', '08:05:03',0, 45);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (3, 17, 32, '2019-01-05', '10:05:02',0, 30);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (4, 21, 33, '2019-04-05', '01:05:05',0, 55);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (5, 10, 31, '2019-07-05', '07:05:02',0, 140);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (6, 6, 28, '2019-08-05', '02:05:05',0, 60);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (7, 2, 30, '2019-12-05', '01:05:05',0, 50);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (8, 8, 25, '2019-10-05', '06:05:05',0, 45);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (9, 1, 24, '2019-10-05', '11:05:05',0, 40);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (10, 17, 27, '2019-09-05', '07:05:03',0, 30);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (11, 6, 29, '2019-09-05', '04:09:02',0, 60);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (12, 2, 26, '2019-08-05', '03:01:01',0, 50);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (1, 21, 32, '2019-10-10', '04:02:05',0, 55);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (1, 17, 23, '2019-11-05', '05:02:03',0, 30);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (2, 11, 3, '2018-10-10', '10:20:05', 0, 65);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (2, 11, 7, '2018-11-03', '02:20:05', 0, 65);
INSERT INTO sessions ( test_id, tutor_id, student_id, date, time, complete, current_rate) VALUES (2, 11, 7, '2018-09-03', '04:05:05', 0, 65);

--- Earnings
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-06-25', 11, 130);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-06-25', 1, 40);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-06-25', 2, 100);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-06-25', 6, 60);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-06-26', 11, 65);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-06-26', 1, 40);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-06-26', 2, 150);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-06-26', 6, 120);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-06-27', 11, 65);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-06-27', 1, 80);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-06-27', 2, 50);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-06-27', 6, 60);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-06-28', 11, 260);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-06-28', 1, 120);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-06-28', 2, 200);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-06-28', 6, 60);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-06-29', 11, 65);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-06-29', 1, 40);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-06-29', 2, 50);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-06-29', 6, 60);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-06-30', 11, 65);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-06-30', 1, 80);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-06-30', 2, 250);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-06-30', 6, 120);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-01', 11, 195);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-01', 1, 120);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-01', 2, 150);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-01', 6, 180);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-02', 11, 195);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-02', 1, 160);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-02', 2, 250);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-02', 6, 60);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-03', 11, 65);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-03', 1, 40);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-03', 2, 150);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-03', 6, 120);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-04', 11, 130);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-04', 1, 120);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-04', 2, 250);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-04', 6, 180);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-05', 11, 130);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-05', 1, 40);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-05', 2, 100);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-05', 6, 120);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-06', 11, 130);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-06', 1, 120);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-06', 2, 50);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-06', 6, 60);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-07', 11, 130);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-07', 1, 160);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-07', 2, 200);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-07', 6, 60);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-08', 11, 130);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-08', 1, 200);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-08', 2, 50);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-08', 6, 120);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-09', 11, 130);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-09', 1, 40);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-09', 2, 50);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-09', 6, 60);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-10', 11, 130);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-10', 1, 160);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-10', 2, 50);
INSERT INTO earnings (date, tutor_id, day_earnings) VALUES ('2018-07-10', 6, 240);

